# Generated by Django 4.0.4 on 2022-05-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basenavigation',
            options={'ordering': ['my_order']},
        ),
        migrations.AddField(
            model_name='basenavigation',
            name='my_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='basenavigation',
            name='url_name',
            field=models.CharField(choices=[('shop', 'shop'), ('contact', 'contact'), ('about', 'about'), ('home', 'home')], max_length=7),
        ),
    ]
