# Generated by Django 4.0.4 on 2022-05-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0002_alter_basenavigation_options_basenavigation_my_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basenavigation',
            name='url_name',
            field=models.CharField(choices=[('shop', 'shop'), ('contact', 'contact'), ('about', 'about'), ('home', 'home'), ('login', 'login'), ('register', 'register'), ('logout', 'logout')], max_length=8),
        ),
    ]
