# Generated by Django 4.0.4 on 2022-07-12 08:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, validators=[django.core.validators.MinValueValidator(5)])),
                ('second_title', models.CharField(blank=True, max_length=25, null=True, validators=[django.core.validators.MinValueValidator(5)])),
                ('cover_image', models.ImageField(upload_to='banner_photos')),
                ('description', models.TextField(validators=[django.core.validators.MinValueValidator(140)])),
                ('slug_field', models.SlugField(unique=True)),
                ('my_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['my_order'],
            },
        ),
    ]
