# Generated by Django 4.0.4 on 2022-07-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_pages', '0003_ourservices_alter_banner_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ourservices',
            options={'ordering': ['my_order']},
        ),
        migrations.AddField(
            model_name='ourservices',
            name='my_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
