# Generated by Django 4.0.4 on 2022-05-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('In Process', 'In Process'), ('Accepted', 'Accepted'), ('Done', 'Done')], default='In Process', max_length=10),
        ),
    ]
