# Generated by Django 4.0.4 on 2022-05-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_brand_alter_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.ImageField(null=True, upload_to='brand_photos'),
        ),
    ]
