# Generated by Django 4.0.4 on 2022-05-20 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_order_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productgallery',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.productgallery'),
        ),
    ]
