# Generated by Django 4.0.4 on 2022-05-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
